[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_FLAGS = "--prefer-offline --no-audit"

[context.production.environment]
  NODE_ENV = "production"
